// GENERATED by scripts/gen-tag-icons.mjs — do not edit by hand.
// Source of truth: lucide-react __iconNode arrays (see TAG_LUCIDE_MAP below
// for the committed tag-value → lucide-icon mapping table with shape notes).
// Presentation attributes (stroke, width, caps) live on the consuming
// <symbol>/<svg> elements, so glyphs inherit currentColor per tag hue.
export const TAG_ICONS: Record<string, string> = {
  "api_provider": "<rect width=\"20\" height=\"8\" x=\"2\" y=\"2\" rx=\"2\" ry=\"2\"/><rect width=\"20\" height=\"8\" x=\"2\" y=\"14\" rx=\"2\" ry=\"2\"/><line x1=\"6\" x2=\"6.01\" y1=\"6\" y2=\"6\"/><line x1=\"6\" x2=\"6.01\" y1=\"18\" y2=\"18\"/>",
  "coding": "<path d=\"m16 18 6-6-6-6\"/><path d=\"m8 6-6 6 6 6\"/>",
  "image": "<rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\" ry=\"2\"/><circle cx=\"9\" cy=\"9\" r=\"2\"/><path d=\"m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21\"/>",
  "voice": "<path d=\"M2 10v3\"/><path d=\"M6 6v11\"/><path d=\"M10 3v18\"/><path d=\"M14 8v7\"/><path d=\"M18 5v13\"/><path d=\"M22 10v3\"/>",
  "video": "<rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"2\"/><path d=\"M9 9.003a1 1 0 0 1 1.517-.859l4.997 2.997a1 1 0 0 1 0 1.718l-4.997 2.997A1 1 0 0 1 9 14.996z\"/>",
  "hand_verified": "<circle cx=\"12\" cy=\"12\" r=\"10\"/><path d=\"m9 12 2 2 4-4\"/>",
  "social_proof": "<path d=\"M22 17a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 21.286V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2z\"/><path d=\"M7 11h10\"/><path d=\"M7 15h6\"/><path d=\"M7 7h8\"/>",
  "unverified": "<circle cx=\"12\" cy=\"12\" r=\"10\"/><path d=\"M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3\"/><path d=\"M12 17h.01\"/>",
  "none": "<rect width=\"18\" height=\"11\" x=\"3\" y=\"11\" rx=\"2\" ry=\"2\"/><path d=\"M7 11V7a5 5 0 0 1 9.9-1\"/>",
  "required": "<rect width=\"18\" height=\"11\" x=\"3\" y=\"11\" rx=\"2\" ry=\"2\"/><path d=\"M7 11V7a5 5 0 0 1 10 0v4\"/>",
  "expired": "<circle cx=\"12\" cy=\"12\" r=\"10\"/><path d=\"M12 6v6l4 2\"/>"
};

export interface TagIconMeta {
  lucide: string
  note: string
}

export const TAG_LUCIDE_MAP: Record<string, TagIconMeta> = {
    api_provider: { lucide: "server", note: "same two-stacked-racks design" },
    coding: { lucide: "code", note: "identical chevrons" },
    image: { lucide: "image", note: "near-identical frame/mountain/sun" },
    voice: { lucide: "audio-lines", note: "identical waveform bars" },
    video: { lucide: "square-play", note: "rounded-square frame replaces rx-2.5 rect; play glyph kept" },
    hand_verified: { lucide: "circle-check", note: "same circle+check seal" },
    social_proof: { lucide: "message-square-text", note: "bubble keeps its hearsay lines" },
    unverified: { lucide: "circle-question-mark", note: "SHAPE DIFFERS: solid ring instead of dashed ring around the question mark (lucide's circle-help is an alias of this icon)" },
    none: { lucide: "lock-open", note: "open shackle preserved" },
    required: { lucide: "lock", note: "adds keyhole dot absent from the hand-drawn lock" },
    expired: { lucide: "clock", note: "same clock face" },
};
